### ISSUE TITLE
node.js - Module parse failure

### ISSUE THREAD

**Issue by DrJonesCGEye** [influenceth/sdk#27]
Just upgraded from 1.9.# to 1.10.2 and the merkle library is causing an issue.
Can i do something on my end regarding loaders for the '#' character?
I got lost/confused googling but seems it's webpack related.
```
Failed to compile.

./node_modules/influence-utils/lib/merkle.js 12:9
Module parse failed: Unexpected character '#' (12:9)
File was processed with these loaders:
 * ./node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
|    * @param {Number<BigInt>|<String>}
|   */
>   static #sortedHash(a, b) {
|     let aSorted = BigInt(a);
|     let bSorted = BigInt(b);
```

**Comment by charlietilt** [comment]
The # denotes a private property or method in Nodejs. If it is throwing an error for you, it may be due to your node version.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/Private_class_fields

**Comment by DrJonesCGEye** [comment]
Most likely it.  I'm currently running v16.10.0 and the current is 18.14.0.
I had some issues with my host last time but that was a while ago so I'll try again.
Thanks
