### ISSUE TITLE
Create a step and Github Action to publish to npm

### ISSUE THREAD

**Issue by clexmond** [influenceth/sdk#91]
We should include an npm job that builds and publishes the SDK with a specific version, as well as a Github Action that automatically builds a beta version (i.e. `2.1.0-beta.123`) based on the current version.

**Comment by Joy-Adah** [comment]
Can I be assigned this?

**Comment by martinvibes** [comment]
is this issue still open for contributions?

**Comment by lindsaymb15** [comment]
Hi! @clexmond My name is Lindsay Morales. I'm a Software Engineer based in Costa Rica and this is my third OD hack!

I'd love to have the opportunity to tackle this issue, and be able to learn more about this project. I've implemented GitHub Actions on some work projects I have worked on, so I already have knowledge on how to implement this. 

How? First I'll research about npm jobs to publish sdks. And for the GH action, under the .github/workflows directory I'd create a main.yml file where I'd define the desired workflow/pipeline for the build.

**Comment by lindsaymoralesb** [comment]
Hi! @clexmond My name is Lindsay Morales. I'm a Software Engineer based in Costa Rica and this is my third OD hack!

I'd love to have the opportunity to tackle this issue, and be able to learn more about this project. I've implemented GitHub Actions on some work projects I have worked on, so I already have knowledge on how to implement this.

How? First I'll research about npm jobs to publish sdks. And for the GH action, under the .github/workflows directory I'd create a main.yml file where I'd define the desired workflow/pipeline for the build.

**Comment by MariangelaNM** [comment]
Hi, I’m Mariangela and I searching my first contribution in this project. 
Possible solution:

- Step 1: Environment Setup
     Configure package.json: Ensure you have a package.json file with scripts for building (build) and publishing (publish) your SDK.

- Step 2: GitHub Action Setup (main.yml)
Create a YAML file: In the .github/workflows directory, create a main.yml file.
Define the workflow:
Use the push event on the main branch as the trigger.
Define a job that runs on ubuntu-latest.
Steps to the installs…

- Step 3: GitHub Action for Beta Version
Retrieve and generate beta version:
Use a script to fetch the current version and generate a new beta version 
Set up another job in main.yml:
Define a separate job for the beta version.
Use a similar workflow as the main job, but with specific commands for the beta version.

**Comment by clexmond** [comment]
> Hi! @clexmond My name is Lindsay Morales. I'm a Software Engineer based in Costa Rica and this is my third OD hack!
> 
> I'd love to have the opportunity to tackle this issue, and be able to learn more about this project. I've implemented GitHub Actions on some work projects I have worked on, so I already have knowledge on how to implement this.
> 
> How? First I'll research about npm jobs to publish sdks. And for the GH action, under the .github/workflows directory I'd create a main.yml file where I'd define the desired workflow/pipeline for the build.

Would you mind joining our Discord and going to the #odhack channel: https://discord.gg/influenceth

**Comment by lindsaymoralesb** [comment]
Sure, np! I already joined the discord @clexmond Should I ping you there?

**Comment by clexmond** [comment]
> Sure, np! I already joined the discord @clexmond Should I ping you there?

Yes please! @DarkosNightmare in #odhack would be perfect

**Comment by lindsaymoralesb** [comment]
> > Sure, np! I already joined the discord @clexmond Should I ping you there?
> 
> Yes please! @DarkosNightmare in #odhack would be perfect

Done
